name = "farm-worker"
main = "src/index.ts"
compatibility_date = "2026-05-13"

[[durable_objects.bindings]]
name = "DISPATCHER"
class_name = "Dispatcher"

[[migrations]]
tag = "v1"
new_classes = ["Dispatcher"]
